version: '3.8'

services:
  # Serviço da nossa API DocIntel
  api:
    build: .
    container_name: docintel_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

  # Serviço do Ollama para rodar os modelos localmente no container
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
